export enum OrderPayActionTypes {
  ORDER_PAY_REQUEST_START = "ORDER_PAY_REQUEST_START",
  ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS",
  ORDER_PAY_FAILURE = "ORDER_PAY_FAILURE",
  ORDER_PAY_RESET = "ORDER_PAY_RESET",
}
