export enum OrderDetailActionTypes {
  ORDER_DETAIL_REQUEST_START = "ORDER_DETAIL_REQUEST_START",
  ORDER_DETAIL_REQUEST_SUCCESS = "ORDER_DETAIL_REQUEST_SUCCESS",
  ORDER_DETAIL_REQUEST_FAILURE = "ORDER_DETAIL_REQUEST_FAILURE",
}
