export enum OrderCreateActionTypes {
  ORDER_CREATE_START = "ORDER_CREATE_START",
  ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS",
  ORDER_CREATE_FAILURE = "ORDER_CREATE_FAILURE",
  ORDER_CREATE_RESET = "ORDER_CREATE_RESET",
}
