export enum UserListTypes {
  USER_LIST_REQUEST_START = "USER_LIST_REQUEST_START",
  USER_LIST_SUCCESS = "USER_LIST_SUCCESS",
  USER_LIST_FAILURE = "USER_LIST_FAILURE",
  USER_LIST_RESET = "USER_LIST_RESET",
  USER_DELETE_REQUEST_START = "  USER_DELETE_REQUEST_START",
  USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS",
  USER_DELETE_FAILURE = "  USER_DELETE_FAILURE",
}
