export enum ProductUpdateActionTypes {
  PRODUCT_UPDATE_REQUEST_START = "PRODUCT_UPDATE_REQUEST_START",
  PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS",
  PRODUCT_UPDATE_FAILURE = "PRODUCT_UPDATE_FAILURE",
  PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET",
}
