export enum MyOrderListTypes {
  MY_ORDER_LIST_REQUEST_START = "MY_ORDER_LIST_REQUEST_START",
  MY_ORDER_LIST_SUCCESS = "MY_ORDER_LIST_SUCCESS",
  MY_ORDER_LIST_FAILURE = "MY_ORDER_LIST_FAILURE",
  MY_ORDER_LIST_RESET = "MY_ORDER_LIST_RESET",
}
