export enum CarouselProductsActionTypes {
  CAROUSEL_PRODUCTS_REQUEST_START = " CAROUSEL_PRODUCTS_REQUEST_START",
  CAROUSEL_PRODUCTS_SUCCESS = "CAROUSEL_PRODUCTS_SUCCESS",
  CAROUSEL_PRODUCTS_FAILURE = "CAROUSEL_PRODUCTS_FAILURE",
}
