export enum UserDetailTypes {
  USER_DETAILS_START = "USER_DETAILS_START",
  USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS",
  USER_DETAILS_FAILURE = "USER_DETAILS_FAILURE",
  USER_DETAILS_RESET = "USER_DETAILS_RESET",
}
