export enum AdminOrderListTypes {
  ADMIN_ORDER_LIST_REQUEST_START = "ADMIN_ORDER_LIST_REQUEST_START",
  ADMIN_ORDER_LIST_SUCCESS = "ADMIN_ORDER_LIST_SUCCESS",
  ADMIN_ORDER_LIST_FAILURE = "ADMIN_ORDER_LIST_FAILURE",
  ORDER_DELIVER_REQUEST_START = "ORDER_DELIVER_REQUEST_START",
  ORDER_DELIVER_SUCCESS = "ORDER_DELIVER_SUCCESS",
  ORDER_DELIVER_FAILURE = "ORDER_DELIVER_FAILURE",
  ORDER_DELIVER_RESET = "ORDER_DELIVER_RESET",
}
